require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "FanzaActresses", type: :request do
  let(:actress) { create :fanza_actress }

  describe "GET /fanza_actresses" do
    it "works" do
      get fanza_actresses_path
      expect(response).to have_http_status(200)
    end
  end

  describe "GET /fanza_actresses/:id" do
    it "works" do
      get fanza_actress_path(actress)
      expect(response).to have_http_status(200)
    end

    it "accept json format" do
      get fanza_actress_path(actress, format: :json)
      expect(response).to have_http_status(200)
    end
  end

  describe "GET /fanza_actresses/:name" do
    it "works with known name" do
      get fanza_actress_path(actress.name)
      expect(response).to have_http_status(200)
    end

    it "works with unknown name" do
      get fanza_actress_path("UNKNOWN")
      expect(response).to have_http_status(200)
    end
  end

  context "when hidden" do
    let(:hidden_actress) { create :fanza_actress, is_hidden: true }

    describe "GET /fanza_actresses/:id" do
      it "returns not found" do
        expect {
          get fanza_actress_path(hidden_actress)
        }.to raise_error(ActiveRecord::RecordNotFound)
      end
    end

    describe "GET /fanza_actresses/:name" do
      it "returns not found" do
        expect {
          get fanza_actress_path(hidden_actress.name)
        }.to raise_error(ActiveRecord::RecordNotFound)
      end
    end
  end
end
